# Generated by Django 3.2.5 on 2021-07-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card',
            field=models.CharField(choices=[('num1', '7'), ('num2', '2'), ('num3', '10'), ('num4', '1'), ('num5', '4')], max_length=10),
        ),
    ]
