# Generated by Django 3.2.5 on 2021-07-23 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(choices=[('num1', '3'), ('num2', '1'), ('num3', '6'), ('num4', '9'), ('num5', '5')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='result',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rule',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('player1', '송경'), ('player2', '지수'), ('player3', '건모'), ('player4', '정훈'), ('player5', '지민')], max_length=20)),
                ('sum', models.IntegerField(default=0)),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.card')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='challenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='users.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='users.user'),
        ),
    ]
