# Generated by Django 3.2.5 on 2021-07-23 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210723_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card',
            field=models.CharField(choices=[('num1', '4'), ('num2', '9'), ('num3', '1'), ('num4', '2'), ('num5', '3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='challenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='rule',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
