# Generated by Django 3.2.5 on 2021-07-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210723_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card',
            field=models.CharField(choices=[('num1', '2'), ('num2', '9'), ('num3', '4'), ('num4', '7'), ('num5', '5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
