# Generated by Django 3.2.5 on 2021-07-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210723_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='challengerCard',
            field=models.CharField(choices=[('num1', '7'), ('num2', '10'), ('num3', '3'), ('num4', '8'), ('num5', '6')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='opponentCard',
            field=models.CharField(choices=[('num1', '7'), ('num2', '10'), ('num3', '3'), ('num4', '8'), ('num5', '6')], default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='card',
            field=models.CharField(choices=[('num1', '8'), ('num2', '0'), ('num3', '7'), ('num4', '9'), ('num5', '3')], max_length=10),
        ),
    ]
