# Generated by Django 3.2.5 on 2021-07-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210723_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card',
            field=models.CharField(choices=[('num1', '1'), ('num2', '5'), ('num3', '10'), ('num4', '3'), ('num5', '0')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='challengerCard',
            field=models.CharField(choices=[('num1', '7'), ('num2', '10'), ('num3', '5'), ('num4', '0'), ('num5', '6')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponentCard',
            field=models.CharField(choices=[('num1', '7'), ('num2', '10'), ('num3', '5'), ('num4', '0'), ('num5', '6')], default=None, max_length=10, null=True),
        ),
    ]
