# Generated by Django 3.2.5 on 2021-07-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210723_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card',
            field=models.CharField(choices=[('num1', '9'), ('num2', '6'), ('num3', '8'), ('num4', '0'), ('num5', '10')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='challengerCard',
            field=models.CharField(choices=[('10', '10'), ('4', '4'), ('8', '8'), ('5', '5'), ('7', '7')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponentCard',
            field=models.CharField(choices=[('10', '10'), ('4', '4'), ('8', '8'), ('5', '5'), ('7', '7')], default=None, max_length=10, null=True),
        ),
    ]
