# Generated by Django 3.2.5 on 2021-07-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210723_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card',
            field=models.CharField(choices=[('num1', '0'), ('num2', '7'), ('num3', '9'), ('num4', '1'), ('num5', '8')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='challengerCard',
            field=models.CharField(choices=[('8', '8'), ('0', '0'), ('2', '2'), ('6', '6'), ('3', '3')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponentCard',
            field=models.CharField(choices=[('8', '8'), ('0', '0'), ('2', '2'), ('6', '6'), ('3', '3')], default=None, max_length=10, null=True),
        ),
    ]
